### ISSUE TITLE
dbus-serialbattery v1.5.20241215 temperature related errors

### ISSUE THREAD

**Issue by entropia1ac** [mr-manuel/venus-os_dbus-serialbattery#128]
### Describe the bug

1/ no alarm in case of temperature sensor damage (e.g. short circuit) JkBMS BT application shows T4=NA and Cerbo shows the last measured value T4= 16C.
![20241216_144325](https://github.com/user-attachments/assets/33769b2e-6137-4cb4-b489-0851ef37c83b)
![20241216_144340](https://github.com/user-attachments/assets/96b2647d-4ec3-4da3-bd75-fc0e6806c692)
2/ incorrect numbering of temperature sensors reported to cerbo T4 is reported as T3
![20241216_145448](https://github.com/user-attachments/assets/6cdfa739-5612-46ff-9480-3776be5fbe61)
3/ incorrectly reported temperature value to VRM, e.g. T alarm=90C is reported as 15.7C
![20241216_145159](https://github.com/user-attachments/assets/e111ba77-2dd0-4e70-8231-6143bc9adedc)

### How to reproduce

make a short circuit on the temperature sensor, for example T4

### Expected behavior

temperature alarm expected

### Driver version of the currently installed driver

v1.5.20241215

### Venus OS device type

Cerbo GX

### Venus OS version

V3.40

### BMS type

JKBMS Inverter (JKBMS PB Model)

### Cell count

16

### Battery count

3

### Connection type

Serial USB adapter to RS485

### Config file

```ini
meaningless
```

### Relevant log output

```shell
meaningless
```

**Comment by mr-manuel** [comment]
What have you configured in the JKBMS app? Since the BMS raises the error. The driver only displays it.

**Comment by entropia1ac** [comment]
![1000005477](https://github.com/user-attachments/assets/ecc4f3bf-6163-4087-96c0-2b1ee528de6f)
![1000005478](https://github.com/user-attachments/assets/0044ef45-cc2b-4bb4-b2ec-936e6d6569a5)

**Comment by KoljaWindeler** [comment]
wow you're doing interesting stuff :D 
how comfortable are you with editing some line of the bms code to provide extra debug info? 
we need the output of the serial communication

https://github.com/mr-manuel/venus-os_dbus-serialbattery/blob/79c8c60ca5d8ba5d517bd2071b7368a7100b1856/dbus-serialbattery/bms/jkbms_pb.py#L173

here are three lines that need the be activated. once they are enabled you should be able to restart the driver and see the data in the output (let me know if you don't know how / where)

JKW

**Comment by KoljaWindeler** [comment]
Actually it might be correct behavior that the sensor doesn't update.

There is a flag that the BMS sets if a sensor is connected or not. so if the BMS tells us the sensor is not connected then the code will not  update it.

I guess testing over temperature with a short might not be the correct way. Can you test with a resistor / poti?

**Comment by mr-manuel** [comment]
The temperature sensor numbering should have been already fixed with https://github.com/mr-manuel/venus-os_dbus-serialbattery/issues/75.

**Comment by entropia1ac** [comment]
@KoljaWindeler - when simulating the alarm with a resistor (1k in parallel) it is ok, Cerbo signals a 90C alarm.

**Comment by KoljaWindeler** [comment]
nice, so to confirm: you get the alarm in the Alarms sub menu here 
![image](https://github.com/user-attachments/assets/9f99779c-d0ac-4d5f-a8cf-4d07c60f6563)

AND get a 90c reading here
![image](https://github.com/user-attachments/assets/dabfb813-e654-4b90-9f14-a336968961be)

right? 

What and where to you still see the 15.7 in VRM? Remote console? can you post a screenshot?
Thanks JKW

**Comment by entropia1ac** [comment]
In Cerbo the alarm signal is correct: sound signal and temperature 90°
15.7 C can be seen in Cerbo in the notification (photo no. 3 above)
There is no alarm in VRM -  is only a temperature jump but up to 50C instead of 90C
![SmartSelect_20241217_155553_VRM](https://github.com/user-attachments/assets/c8e42747-d30e-453c-bd4d-a856702c38ba)
![SmartSelect_20241217_155626_VRM](https://github.com/user-attachments/assets/a3642f22-119c-4c17-892d-d8d193542809)

**Comment by entropia1ac** [comment]
Maybe, but the VRM did not signal a high temperature alarm.

**Comment by KoljaWindeler** [comment]
i guess there is very little that we can do about it .. the driver can only forward the values from the BMS to Victron. Everything after that is out of the hands of this driver.

might also be due to way how you manipulate the data .. you could try a poti and slowly lower the value, similar to how a temperature could rise. maybe there is some sort of outlier / lowpass filter 

@entropia1ac i guess we can close this here, right?

**Comment by mr-manuel** [comment]
@entropia1ac you wrote the config file is meaningless, but it is not. Depending on how you use the temperature sensors and how you set your temperature config, different values are used. By default the battery temperature is fetched from all available sensors except MOS. The value from the temperature alarms get the value from `/Dc/0/Temperature`.

https://github.com/victronenergy/venus-platform/blob/400123f027a15bc59aac14f4db063e559c95d43a/src/alarm_item.cpp#L301-L330
